//! Published-repository core: extract manifest metadata from uploaded
//! archives, land them under `repo_dir`, and regenerate `index.toml` in the
//! exact shape sage's channel reader consumes.

use std::io::Read;
use std::path::Path;

use anyhow::{bail, Context, Result};

use crate::config::Config;
use crate::db;
use crate::status::{self, State as BuildState};

/// The `[package]` section of a package's `.METADATA/manifest.toml` — the
/// authoritative description of an upload. Stored as JSON in the published
/// table so index regeneration never re-reads archives.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ManifestMeta {
    pub name: String,
    pub version: String,
    pub release: String,
    #[serde(default)]
    pub epoch: i64,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub license: String,
    #[serde(default)]
    pub channel: String,
    #[serde(default)]
    pub arch: String,
    #[serde(default)]
    pub installed_size: i64,
    // Build provenance, all optional.
    #[serde(default)]
    pub build_compiler: String,
    #[serde(default)]
    pub build_compiler_version: String,
    #[serde(default)]
    pub build_cflags: String,
    #[serde(default)]
    pub build_cxxflags: String,
    #[serde(default)]
    pub build_ldflags: String,
    #[serde(default)]
    pub dependencies: Vec<String>,
    #[serde(default)]
    pub provides: Vec<String>,
    #[serde(default)]
    pub conffiles: Vec<String>,
}

/// Server receipt for one publish, including the freshly derived build state.
#[derive(Debug, serde::Serialize)]
pub struct Receipt {
    pub filename: String,
    pub name: String,
    pub version: String,
    pub release: String,
    pub size: i64,
    pub sha256: String,
    pub state: BuildState,
}

/// Filenames are generated by `sage build`; accept only that shape so the
/// static route can never be talked into path tricks.
pub fn valid_filename(name: &str) -> bool {
    name.len() <= 255
        && name.ends_with(".pkg.tar.zst")
        && !name.starts_with('.')
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | '+'))
}

/// Pull `.METADATA/manifest.toml` out of a streamed-then-flushed archive.
pub fn read_manifest_meta(archive: &Path) -> Result<ManifestMeta> {
    let file = std::fs::File::open(archive)
        .with_context(|| format!("cannot reopen {}", archive.display()))?;
    let decoder = zstd::Decoder::new(file)?;
    let mut tar = tar::Archive::new(decoder);
    for entry in tar.entries()? {
        let mut entry = entry?;
        let path = entry.path()?.to_path_buf();
        if path.file_name().is_some_and(|n| n == "manifest.toml")
            && path.parent().is_some_and(|d| d.ends_with(".METADATA"))
        {
            let mut text = String::new();
            entry.read_to_string(&mut text)?;
            return parse_manifest(&text);
        }
    }
    bail!("archive has no .METADATA/manifest.toml");
}

/// Pull the `.METADATA/files.idx` inventory (TSV: type/mode/size/sha256/path/
/// target) out of an archive; only what browsing needs is kept.
pub fn read_file_list(archive: &Path) -> Result<Vec<db::FileLine>> {
    let file = std::fs::File::open(archive)?;
    let decoder = zstd::Decoder::new(file)?;
    let mut tar = tar::Archive::new(decoder);
    for entry in tar.entries()? {
        let mut entry = entry?;
        let path = entry.path()?.to_path_buf();
        if path.file_name().is_some_and(|n| n == "files.idx")
            && path.parent().is_some_and(|d| d.ends_with(".METADATA"))
        {
            let mut text = String::new();
            entry.read_to_string(&mut text)?;
            return Ok(text
                .lines()
                .filter(|l| !l.starts_with('#'))
                .filter_map(|l| {
                    let cols: Vec<&str> = l.split('\t').collect();
                    if cols.len() < 5 {
                        return None;
                    }
                    Some(db::FileLine {
                        kind: cols[0].to_string(),
                        size: cols[2].parse().unwrap_or(0),
                        path: cols[4].to_string(),
                    })
                })
                .collect());
        }
    }
    Ok(Vec::new()) // legacy archives without files.idx
}

fn parse_manifest(text: &str) -> Result<ManifestMeta> {
    let doc: toml::Table = toml::from_str(text).context("manifest.toml is not valid TOML")?;
    let pkg = doc
        .get("package")
        .and_then(|v| v.as_table())
        .context("manifest has no [package] table")?;
    let s = |k: &str| {
        pkg.get(k)
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string()
    };
    let i = |k: &str| pkg.get(k).and_then(|v| v.as_integer()).unwrap_or(0);
    let arr = |k: &str| -> Vec<String> {
        pkg.get(k)
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|v| v.as_str().map(str::to_string))
                    .collect()
            })
            .unwrap_or_default()
    };
    let meta = ManifestMeta {
        name: s("name"),
        version: s("version"),
        release: s("release"),
        epoch: i("epoch"),
        description: s("description"),
        license: s("license"),
        channel: s("channel"),
        arch: s("arch"),
        installed_size: i("installed_size"),
        build_compiler: s("build_compiler"),
        build_compiler_version: s("build_compiler_version"),
        build_cflags: s("build_cflags"),
        build_cxxflags: s("build_cxxflags"),
        build_ldflags: s("build_ldflags"),
        dependencies: arr("dependencies"),
        provides: arr("provides"),
        conffiles: arr("conffiles"),
    };
    if meta.name.is_empty() || meta.version.is_empty() {
        bail!("manifest is missing name or version");
    }
    Ok(meta)
}

/// Land a fully-written, already-hashed temp file as a published package:
/// verify declared hash, extract meta, move into place, upsert, re-index.
pub fn ingest(
    conn: &rusqlite::Connection,
    cfg: &Config,
    tmp_path: &Path,
    filename: &str,
    sha256: &str,
    declared_sha: Option<&str>,
    builder: &str,
) -> Result<Receipt> {
    if !valid_filename(filename) {
        bail!("invalid package filename '{filename}'");
    }
    if let Some(want) = declared_sha {
        if want != sha256 {
            bail!("sha256 mismatch: client sent {want}, server received {sha256}");
        }
    }
    let meta = read_manifest_meta(tmp_path)?;
    // File list is best-effort: legacy archives without files.idx still publish.
    let files = read_file_list(tmp_path).unwrap_or_default();
    let size = std::fs::metadata(tmp_path)?.len();
    let dest = cfg.repo_dir.join(filename);
    std::fs::rename(tmp_path, &dest)
        .with_context(|| format!("cannot move upload into {}", dest.display()))?;
    db::upsert_published(conn, filename, &meta, size as i64, sha256, builder)?;
    db::replace_published_files(conn, filename, &files)?;
    regenerate_index(conn, cfg)?;

    let recipe = db::package_by_name(conn, &meta.name)?;
    let state = match &recipe {
        Some(r) => status::derive(&r.version, &r.release, Some((&meta.version, &meta.release))),
        None => BuildState::Missing,
    };
    Ok(Receipt {
        filename: filename.to_string(),
        name: meta.name,
        version: meta.version,
        release: meta.release,
        size: size as i64,
        sha256: sha256.to_string(),
        state,
    })
}

/// Withdraw a published artifact: DB rows, build log, on-disk file, re-index.
pub fn unpublish(conn: &rusqlite::Connection, cfg: &Config, filename: &str) -> Result<()> {
    if !valid_filename(filename) {
        bail!("invalid package filename '{filename}'");
    }
    let existed = db::delete_published(conn, filename)?;
    if !existed {
        bail!("'{filename}' is not published");
    }
    match std::fs::remove_file(cfg.repo_dir.join(filename)) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e).context("cannot remove repository file"),
    }
    regenerate_index(conn, cfg)?;
    Ok(())
}

/// Rebuild `index.toml` from the published table, byte-compatible with what
/// `sage repo index` emits (schema_version 1 + [[packages]] rows).
pub fn regenerate_index(conn: &rusqlite::Connection, cfg: &Config) -> Result<()> {
    std::fs::create_dir_all(&cfg.repo_dir)?;
    let mut out = String::from("schema_version = 1\n\n[channel]\nname = \"sclinux\"\n");
    out.push_str(&format!("updated_at = \"{}\"\n\n", rfc3339_now()));

    for row in db::index_rows(conn)? {
        if row.meta_json.is_empty() {
            continue; // pre-P3 row without extracted meta
        }
        let m: ManifestMeta =
            serde_json::from_str(&row.meta_json).context("stored manifest meta is corrupt")?;
        out.push_str("[[packages]]\n");
        let _ = (
            w(&mut out, "name", &m.name),
            w(&mut out, "version", &m.version),
            w(&mut out, "release", &m.release),
        );
        if m.epoch > 0 {
            out.push_str(&format!("epoch = {}\n", m.epoch));
        }
        let _ = (
            w(&mut out, "description", &m.description),
            w(&mut out, "license", &m.license),
            w(&mut out, "channel", &m.channel),
            w(&mut out, "arch", &m.arch),
        );
        out.push_str(&format!("installed_size = {}\n", m.installed_size));
        out.push_str(&format!("file = \"{}\"\n", escape(&row.filename)));
        for (k, v) in [
            ("build_compiler", &m.build_compiler),
            ("build_compiler_version", &m.build_compiler_version),
            ("build_cflags", &m.build_cflags),
            ("build_cxxflags", &m.build_cxxflags),
            ("build_ldflags", &m.build_ldflags),
        ] {
            if !v.is_empty() {
                out.push_str(&format!("{k} = \"{}\"\n", escape(v)));
            }
        }
        push_array(&mut out, "dependencies", &m.dependencies);
        push_array(&mut out, "provides", &m.provides);
        if !m.conffiles.is_empty() {
            push_array(&mut out, "conffiles", &m.conffiles);
        }
        out.push('\n');
    }

    // Atomic swap so a concurrent /repo/index.toml read never sees a half file.
    let tmp = cfg.repo_dir.join(".index.toml.tmp");
    std::fs::write(&tmp, &out)?;
    std::fs::rename(&tmp, cfg.repo_dir.join("index.toml"))?;
    Ok(())
}

fn w(out: &mut String, key: &str, value: &str) {
    out.push_str(&format!("{key} = \"{}\"\n", escape(value)));
}

fn push_array(out: &mut String, key: &str, values: &[String]) {
    out.push_str(&format!("{key} = [\n"));
    for v in values {
        out.push_str(&format!("    \"{}\",\n", escape(v)));
    }
    out.push_str("]\n");
}

/// Escape a TOML basic string body (mirrors sage's escape_toml_basic_string).
fn escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\u{8}' => out.push_str("\\b"),
            '\t' => out.push_str("\\t"),
            '\n' => out.push_str("\\n"),
            '\u{c}' => out.push_str("\\f"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// RFC3339 UTC timestamp for index.toml's updated_at.
fn rfc3339_now() -> String {
    db::time_utc(db::now())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filenames() {
        assert!(valid_filename("gcc-15.3.0-1-x86_64.pkg.tar.zst"));
        assert!(!valid_filename("../evil.pkg.tar.zst"));
        assert!(!valid_filename(".hidden.pkg.tar.zst"));
        assert!(!valid_filename("pkg.zip"));
        assert!(!valid_filename("has space.pkg.tar.zst"));
    }

    #[test]
    fn timestamps() {
        let t = rfc3339_now();
        assert_eq!(t.len(), 20);
        assert!(t.ends_with('Z'));
        assert_eq!(&t[4..5], "-");
    }

    #[test]
    fn escaping() {
        assert_eq!(escape(r#"a"b\c"#), r#"a\"b\\c"#);
        assert_eq!(escape("\n"), "\\n");
    }
}
