//! Published-repository core: extract manifest metadata from uploaded
//! archives, land them under `repo_dir`, and regenerate `index.toml` in the
//! exact shape sage's channel reader consumes.

use std::io::Read;
use std::path::Path;

use anyhow::{bail, Context, Result};

use crate::config::Config;
use crate::db;
use crate::status::{self, State as BuildState};

/// A tool Sage configured and directly probed for a managed recipe-v2 build.
/// Empty on v1 and upstream-prebuilt/repackaged archives.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ManagedBuildTool {
    pub role: String,
    pub executable: String,
    pub family: String,
    pub version: String,
    /// Non-empty flag channels Sage actually configured for this archive.
    /// Stored as `ENV=value`; never inferred from the resulting binaries.
    #[serde(default)]
    pub parameters: Vec<String>,
}

fn valid_managed_parameter(parameter: &str) -> bool {
    let Some((name, value)) = parameter.split_once('=') else {
        return false;
    };
    let mut chars = name.chars();
    matches!(chars.next(), Some(c) if c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
        && !value.is_empty()
}

/// The `[package]` section of a package's `.METADATA/manifest.toml` — the
/// authoritative description of an upload. Stored as JSON in the published
/// table so index regeneration never re-reads archives.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct ManifestMeta {
    pub name: String,
    pub version: String,
    pub release: String,
    #[serde(default)]
    pub epoch: i64,
    #[serde(default)]
    pub description: String,
    #[serde(default)]
    pub license: String,
    #[serde(default)]
    pub channel: String,
    #[serde(default)]
    pub arch: String,
    #[serde(default)]
    pub installed_size: i64,
    /// Raw universal service definition; non-empty marks a daemon package.
    #[serde(default)]
    pub service_toml: String,
    #[serde(default)]
    pub dependencies: Vec<String>,
    #[serde(default)]
    pub provides: Vec<String>,
    #[serde(default)]
    pub conffiles: Vec<String>,
    #[serde(default)]
    pub managed_build_tools: Vec<ManagedBuildTool>,
}

/// Server receipt for one publish, including the freshly derived build state.
#[derive(Debug, serde::Serialize)]
pub struct Receipt {
    pub filename: String,
    pub name: String,
    pub version: String,
    pub release: String,
    pub size: i64,
    pub sha256: String,
    pub state: BuildState,
}

/// Filenames are generated by `sage build`; accept only that shape so the
/// static route can never be talked into path tricks.
pub fn valid_filename(name: &str) -> bool {
    name.len() <= 255
        && name.ends_with(".pkg.tar.zst")
        && !name.starts_with('.')
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-' | '+'))
}

/// Pull `.METADATA/manifest.toml` out of a streamed-then-flushed archive.
pub fn read_manifest_meta(archive: &Path) -> Result<ManifestMeta> {
    let file = std::fs::File::open(archive)
        .with_context(|| format!("cannot reopen {}", archive.display()))?;
    let decoder = zstd::Decoder::new(file)?;
    let mut tar = tar::Archive::new(decoder);
    for entry in tar.entries()? {
        let mut entry = entry?;
        let path = entry.path()?.to_path_buf();
        if path.file_name().is_some_and(|n| n == "manifest.toml")
            && path.parent().is_some_and(|d| d.ends_with(".METADATA"))
        {
            let mut text = String::new();
            entry.read_to_string(&mut text)?;
            return parse_manifest(&text);
        }
    }
    bail!("archive has no .METADATA/manifest.toml");
}

/// Pull the `.METADATA/files.idx` inventory (TSV: type/mode/size/sha256/path/
/// target) out of an archive; only what browsing needs is kept.
pub fn read_file_list(archive: &Path) -> Result<Vec<db::FileLine>> {
    let file = std::fs::File::open(archive)?;
    let decoder = zstd::Decoder::new(file)?;
    let mut tar = tar::Archive::new(decoder);
    for entry in tar.entries()? {
        let mut entry = entry?;
        let path = entry.path()?.to_path_buf();
        if path.file_name().is_some_and(|n| n == "files.idx")
            && path.parent().is_some_and(|d| d.ends_with(".METADATA"))
        {
            let mut text = String::new();
            entry.read_to_string(&mut text)?;
            return Ok(text
                .lines()
                .filter(|l| !l.starts_with('#'))
                .filter_map(|l| {
                    let cols: Vec<&str> = l.split('\t').collect();
                    if cols.len() >= 9 {
                        // Modern Sage 9-column v2 format: type\tmode\tuid\tgid\tcaps\tsize\tsha256\tpath\ttarget
                        Some(db::FileLine {
                            kind: cols[0].to_string(),
                            size: cols[5].parse().unwrap_or(0),
                            path: cols[7].to_string(),
                        })
                    } else if cols.len() >= 5 {
                        // Legacy 6-column format: type\tmode\tsize\tsha256\tpath[\ttarget]
                        Some(db::FileLine {
                            kind: cols[0].to_string(),
                            size: cols[2].parse().unwrap_or(0),
                            path: cols[4].to_string(),
                        })
                    } else {
                        None
                    }
                })
                .collect());
        }
    }
    Ok(Vec::new()) // legacy archives without files.idx
}

fn parse_manifest(text: &str) -> Result<ManifestMeta> {
    let doc: toml::Table = toml::from_str(text).context("manifest.toml is not valid TOML")?;
    let schema_version = doc
        .get("schema_version")
        .and_then(|v| v.as_integer())
        .unwrap_or(1);
    let pkg = doc
        .get("package")
        .and_then(|v| v.as_table())
        .context("manifest has no [package] table")?;
    let s = |k: &str| {
        pkg.get(k)
            .and_then(|v| v.as_str())
            .unwrap_or_default()
            .to_string()
    };
    let i = |k: &str| pkg.get(k).and_then(|v| v.as_integer()).unwrap_or(0);
    let arr = |k: &str| -> Vec<String> {
        pkg.get(k)
            .and_then(|v| v.as_array())
            .map(|a| {
                a.iter()
                    .filter_map(|v| v.as_str().map(str::to_string))
                    .collect()
            })
            .unwrap_or_default()
    };
    let managed_build_tools = doc
        .get("managed_build_tools")
        .and_then(|v| v.as_array())
        .map(|tools| {
            tools
                .iter()
                .map(|item| {
                    let tool = item
                        .as_table()
                        .context("managed_build_tools entries must be tables")?;
                    let value = |key: &str| {
                        tool.get(key)
                            .and_then(|v| v.as_str())
                            .unwrap_or_default()
                            .to_string()
                    };
                    let parameters = match tool.get("parameters") {
                        None => Vec::new(),
                        Some(value) => value
                            .as_array()
                            .context("managed_build_tools parameters must be an array")?
                            .iter()
                            .map(|parameter| {
                                parameter
                                    .as_str()
                                    .map(str::to_string)
                                    .context("managed_build_tools parameters must be strings")
                            })
                            .collect::<Result<Vec<_>>>()?,
                    };
                    let observed = ManagedBuildTool {
                        role: value("role"),
                        executable: value("executable"),
                        family: value("family"),
                        version: value("version"),
                        parameters,
                    };
                    let version_argument = value("version_argument");
                    let known = match observed.role.as_str() {
                        "cc" | "cxx" => matches!(observed.family.as_str(), "gcc" | "clang"),
                        "linker" => matches!(observed.family.as_str(), "ld" | "lld" | "mold"),
                        "rustc" => observed.family == "rustc",
                        _ => false,
                    };
                    if !known
                        || observed.executable.is_empty()
                        || observed.version.is_empty()
                        || version_argument != "--version"
                        || observed
                            .parameters
                            .iter()
                            .any(|parameter| !valid_managed_parameter(parameter))
                        || observed
                            .parameters
                            .iter()
                            .collect::<std::collections::HashSet<_>>()
                            .len()
                            != observed.parameters.len()
                    {
                        bail!("invalid managed_build_tools observation");
                    }
                    Ok(observed)
                })
                .collect::<Result<Vec<_>>>()
        })
        .transpose()?
        .unwrap_or_default();
    if !managed_build_tools.is_empty() && schema_version < 2 {
        bail!("managed_build_tools are valid only in manifest schema v2");
    }
    let mut roles = std::collections::HashSet::new();
    if managed_build_tools
        .iter()
        .any(|tool| !roles.insert(tool.role.as_str()))
    {
        bail!("managed_build_tools contains a duplicate role");
    }
    let meta = ManifestMeta {
        name: s("name"),
        version: s("version"),
        release: s("release"),
        epoch: i("epoch"),
        description: s("description"),
        license: s("license"),
        channel: s("channel"),
        // Legacy x86_64 manifests fold into amd64 at the door, so published
        // state meets the recipe's canonical spelling.
        arch: crate::model::canonical_arch(&s("arch")).to_string(),
        installed_size: i("installed_size"),
        service_toml: s("service_toml"),
        dependencies: arr("dependencies"),
        provides: arr("provides"),
        conffiles: arr("conffiles"),
        managed_build_tools,
    };
    if meta.name.is_empty() || meta.version.is_empty() {
        bail!("manifest is missing name or version");
    }
    Ok(meta)
}

/// Land a fully-written, already-hashed temp file as a published package:
/// verify declared hash, extract meta, move into place, upsert, re-index.
pub fn ingest(
    conn: &rusqlite::Connection,
    cfg: &Config,
    tmp_path: &Path,
    filename: &str,
    sha256: &str,
    declared_sha: Option<&str>,
    builder: &str,
) -> Result<Receipt> {
    if !valid_filename(filename) {
        bail!("invalid package filename '{filename}'");
    }
    if let Some(want) = declared_sha {
        if want != sha256 {
            bail!("sha256 mismatch: client sent {want}, server received {sha256}");
        }
    }
    let meta = read_manifest_meta(tmp_path)?;
    // File list is best-effort: legacy archives without files.idx still publish.
    let files = read_file_list(tmp_path).unwrap_or_default();
    let size = std::fs::metadata(tmp_path)?.len();
    let dest = cfg.repo_dir.join(filename);
    std::fs::rename(tmp_path, &dest)
        .with_context(|| format!("cannot move upload into {}", dest.display()))?;
    db::upsert_published(conn, filename, &meta, size as i64, sha256, builder)?;
    db::replace_published_files(conn, filename, &files)?;
    regenerate_index(conn, cfg)?;

    let recipe = db::package_by_name(conn, &meta.name)?;
    let state = match &recipe {
        Some(r) => status::derive(&r.version, &r.release, Some((&meta.version, &meta.release))),
        None => BuildState::Missing,
    };
    Ok(Receipt {
        filename: filename.to_string(),
        name: meta.name,
        version: meta.version,
        release: meta.release,
        size: size as i64,
        sha256: sha256.to_string(),
        state,
    })
}

/// Withdraw a published artifact: DB rows, build log, on-disk file, re-index.
pub fn unpublish(conn: &rusqlite::Connection, cfg: &Config, filename: &str) -> Result<()> {
    if !valid_filename(filename) {
        bail!("invalid package filename '{filename}'");
    }
    let existed = db::delete_published(conn, filename)?;
    if !existed {
        bail!("'{filename}' is not published");
    }
    match std::fs::remove_file(cfg.repo_dir.join(filename)) {
        Ok(()) => {}
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e).context("cannot remove repository file"),
    }
    regenerate_index(conn, cfg)?;
    Ok(())
}

/// Rebuild `index.toml` from the published table, byte-compatible with what
/// `sage repo index` emits (schema_version 1 + [[packages]] rows).
pub fn regenerate_index(conn: &rusqlite::Connection, cfg: &Config) -> Result<()> {
    std::fs::create_dir_all(&cfg.repo_dir)?;
    let mut out = String::from("schema_version = 1\n\n[channel]\nname = \"sclinux\"\n");
    out.push_str(&format!("updated_at = \"{}\"\n\n", rfc3339_now()));

    for row in db::index_rows(conn)? {
        if row.meta_json.is_empty() {
            continue; // pre-P3 row without extracted meta
        }
        let m: ManifestMeta =
            serde_json::from_str(&row.meta_json).context("stored manifest meta is corrupt")?;
        out.push_str("[[packages]]\n");
        let _ = (
            w(&mut out, "name", &m.name),
            w(&mut out, "version", &m.version),
            w(&mut out, "release", &m.release),
        );
        if m.epoch > 0 {
            out.push_str(&format!("epoch = {}\n", m.epoch));
        }
        let _ = (
            w(&mut out, "description", &m.description),
            w(&mut out, "license", &m.license),
            w(&mut out, "channel", &m.channel),
            w(&mut out, "arch", &m.arch),
        );
        out.push_str(&format!("installed_size = {}\n", m.installed_size));
        out.push_str(&format!("file = \"{}\"\n", escape(&row.filename)));
        push_array(&mut out, "dependencies", &m.dependencies);
        push_array(&mut out, "provides", &m.provides);
        if !m.conffiles.is_empty() {
            push_array(&mut out, "conffiles", &m.conffiles);
        }
        for tool in &m.managed_build_tools {
            out.push_str("[[packages.managed_build_tools]]\n");
            let _ = (
                w(&mut out, "role", &tool.role),
                w(&mut out, "executable", &tool.executable),
                w(&mut out, "family", &tool.family),
                w(&mut out, "version", &tool.version),
                w(&mut out, "version_argument", "--version"),
            );
            if !tool.parameters.is_empty() {
                push_array(&mut out, "parameters", &tool.parameters);
            }
        }
        out.push('\n');
    }

    // Atomic swap so a concurrent /repo/index.toml read never sees a half file.
    let tmp = cfg.repo_dir.join(".index.toml.tmp");
    std::fs::write(&tmp, &out)?;
    std::fs::rename(&tmp, cfg.repo_dir.join("index.toml"))?;
    Ok(())
}

fn w(out: &mut String, key: &str, value: &str) {
    out.push_str(&format!("{key} = \"{}\"\n", escape(value)));
}

fn push_array(out: &mut String, key: &str, values: &[String]) {
    out.push_str(&format!("{key} = [\n"));
    for v in values {
        out.push_str(&format!("    \"{}\",\n", escape(v)));
    }
    out.push_str("]\n");
}

/// Escape a TOML basic string body (mirrors sage's escape_toml_basic_string).
fn escape(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for c in value.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\u{8}' => out.push_str("\\b"),
            '\t' => out.push_str("\\t"),
            '\n' => out.push_str("\\n"),
            '\u{c}' => out.push_str("\\f"),
            '\r' => out.push_str("\\r"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out
}

/// RFC3339 UTC timestamp for index.toml's updated_at.
fn rfc3339_now() -> String {
    db::time_utc(db::now())
}

#[cfg(test)]
mod arch_tests {
    use super::*;

    #[test]
    fn manifest_arch_canonicalized() {
        let text =
            "[package]\nname = \"zlib\"\nversion = \"1.3.2\"\nrelease = \"2\"\narch = \"x86_64\"\n";
        let meta = parse_manifest(text).unwrap();
        assert_eq!(meta.arch, "amd64");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filenames() {
        assert!(valid_filename("gcc-15.3.0-1-x86_64.pkg.tar.zst"));
        assert!(!valid_filename("../evil.pkg.tar.zst"));
        assert!(!valid_filename(".hidden.pkg.tar.zst"));
        assert!(!valid_filename("pkg.zip"));
        assert!(!valid_filename("has space.pkg.tar.zst"));
    }

    #[test]
    fn timestamps() {
        let t = rfc3339_now();
        assert_eq!(t.len(), 20);
        assert!(t.ends_with('Z'));
        assert_eq!(&t[4..5], "-");
    }

    #[test]
    fn escaping() {
        assert_eq!(escape(r#"a"b\c"#), r#"a\"b\\c"#);
        assert_eq!(escape("\n"), "\\n");
    }

    #[test]
    fn managed_v2_tools_are_archive_observations() {
        let meta = parse_manifest(
            r#"
schema_version = 2
[package]
name = "v2-example"
version = "1.0"
release = "1"

[[managed_build_tools]]
role = "cc"
executable = "/opt/toolchains/bin/clang"
family = "clang"
version = "22.1.8"
version_argument = "--version"
parameters = ["CFLAGS=-O2 -pipe", "KCFLAGS=-O2 -pipe"]
"#,
        )
        .unwrap();
        assert_eq!(meta.managed_build_tools.len(), 1);
        assert_eq!(
            meta.managed_build_tools[0].executable,
            "/opt/toolchains/bin/clang"
        );
        assert_eq!(meta.managed_build_tools[0].version, "22.1.8");
        assert_eq!(
            meta.managed_build_tools[0].parameters,
            ["CFLAGS=-O2 -pipe", "KCFLAGS=-O2 -pipe"]
        );

        let prebuilt =
            parse_manifest("[package]\nname = \"rust-bin\"\nversion = \"1.90\"\nrelease = \"1\"\n")
                .unwrap();
        assert!(prebuilt.managed_build_tools.is_empty());
    }

    #[test]
    fn files_idx_supports_both_6_and_9_columns() {
        let parse_lines = |text: &str| -> Vec<crate::db::FileLine> {
            text.lines()
                .filter(|l| !l.starts_with('#'))
                .filter_map(|l| {
                    let cols: Vec<&str> = l.split('\t').collect();
                    if cols.len() >= 9 {
                        Some(crate::db::FileLine {
                            kind: cols[0].to_string(),
                            size: cols[5].parse().unwrap_or(0),
                            path: cols[7].to_string(),
                        })
                    } else if cols.len() >= 5 {
                        Some(crate::db::FileLine {
                            kind: cols[0].to_string(),
                            size: cols[2].parse().unwrap_or(0),
                            path: cols[4].to_string(),
                        })
                    } else {
                        None
                    }
                })
                .collect()
        };

        let six_col = "f\t755\t1234\tdeadbeef\tusr/bin/tool\t-\n";
        let res6 = parse_lines(six_col);
        assert_eq!(res6.len(), 1);
        assert_eq!(res6[0].kind, "f");
        assert_eq!(res6[0].size, 1234);
        assert_eq!(res6[0].path, "usr/bin/tool");

        let nine_col = "f\t755\t0\t0\tcap_net_admin=+ep\t5678\tfeedbeef\tusr/bin/admin\t-\n";
        let res9 = parse_lines(nine_col);
        assert_eq!(res9.len(), 1);
        assert_eq!(res9[0].kind, "f");
        assert_eq!(res9[0].size, 5678);
        assert_eq!(res9[0].path, "usr/bin/admin");
    }
}
